- hosts: all
  sudo: yes
  tasks:
    - name: Install packages
      apt: name={{ item }} state=present
      with_items: 
        - git
        - tmux
        - vim
        - cmake
        - autoconf automake binutils-dev build-essential cmake g++ gawk git 
        - libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-regex-dev 
        - libboost-system-dev libboost-thread-dev libboost-context-dev libbz2-dev libc-client-dev libldap2-dev 
        - libc-client2007e-dev libcap-dev libcurl4-openssl-dev libdwarf-dev libelf-dev 
        - libexpat-dev libgd2-xpm-dev libgoogle-glog-dev libgoogle-perftools-dev libicu-dev 
        - libjemalloc-dev libmcrypt-dev libmemcached-dev libmysqlclient-dev libncurses-dev 
        - libonig-dev libpcre3-dev libreadline-dev libtbb-dev libtool libxml2-dev zlib1g-dev 
        - libevent-dev libmagickwand-dev libinotifytools0-dev libiconv-hook-dev libedit-dev 
        - libiberty-dev libxslt1-dev ocaml-native-compilers libsqlite3-dev libyaml-dev libgmp3-dev 
        - gperf libkrb5-dev libnotify-dev

    - git: repo=https://github.com/facebook/hhvm.git 
           dest=/home/vagrant/hhvm 
           force=yes
    - shell : cmake -DMYSQL_UNIX_SOCK_ADDR=/var/run/mysqld/mysqld.sock .
    - shell : make -j [number_of_processor_cores] # eg. make -j 4
    - shell : make install
