- hosts: all
  sudo: yes
  tasks:
    - name: Install packages
      apt: name={{ item }} state=present
      with_items: 
        - git
        - tmux
        - vim
        - cmake
        - build-essential
        - libboost-dev
        - libboost-system-dev
        - libboost-program-options-dev
        - libboost-filesystem-dev
        - libboost-context-dev
        - libgoogle-glog-dev
        - libmysqlclient-dev
        - libmemcache-dev
        - pkg-config

    - git: repo=https://github.com/facebook/hhvm.git 
           dest=/home/vagrant/hhvm 
           force=yes
